version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/libvnc-sys"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/libvnc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
