[package]
name    = "image_capture"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.3"
image      = "0.25.1"
libvnc     = "*"
log        = "0.4.21"


[dev-dependencies]
num-complex = "0.4.5"
