[package]
name = "libvnc-rs"
authors = ["Chiichen <chiichen@qq.com>"]
version = "0.1.0"
edition = "2021"
keywords = ["vnc", "libvnc", "vncserver", "rfb"]
license = "LGPL-3.0-only"
readme = "README.md"


[dependencies]
libvnc-sys = { version = "0.1.0" }
